// <auto-generated />
using System;
using Labb4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220331121619_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb4.Models.Interests", b =>
                {
                    b.Property<int>("interestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("interestName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("interestID");

                    b.HasIndex("PersonID");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            interestID = 1,
                            PersonID = 1,
                            details = "The fine art of making console applications",
                            interestName = "C#"
                        },
                        new
                        {
                            interestID = 2,
                            PersonID = 2,
                            details = "Identifying and managing problems in a relationship",
                            interestName = "SQL"
                        },
                        new
                        {
                            interestID = 3,
                            PersonID = 3,
                            details = "Eliminates various bugs",
                            interestName = "Exterminator"
                        },
                        new
                        {
                            interestID = 4,
                            PersonID = 1,
                            details = "Getting matched with bad teammates and loose games",
                            interestName = "Overwatch"
                        });
                });

            modelBuilder.Entity("Labb4.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            firstName = "Ludwig",
                            lastName = "Oleby",
                            phoneNr = "0736004656"
                        },
                        new
                        {
                            PersonID = 2,
                            firstName = "Sara",
                            lastName = "Sarasson",
                            phoneNr = "0736004657"
                        },
                        new
                        {
                            PersonID = 3,
                            firstName = "Sam",
                            lastName = "Samson",
                            phoneNr = "0736004658"
                        });
                });

            modelBuilder.Entity("Labb4.Models.Websites", b =>
                {
                    b.Property<int>("WebpageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Webpage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("interestsinterestID")
                        .HasColumnType("int");

                    b.HasKey("WebpageID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.HasIndex("interestsinterestID");

                    b.ToTable("websites");

                    b.HasData(
                        new
                        {
                            WebpageID = 1,
                            InterestID = 1,
                            PersonID = 1,
                            Webpage = "www.csharp.com"
                        },
                        new
                        {
                            WebpageID = 2,
                            InterestID = 2,
                            PersonID = 1,
                            Webpage = "www.playoverwatch.com"
                        },
                        new
                        {
                            WebpageID = 3,
                            InterestID = 3,
                            PersonID = 2,
                            Webpage = "www.sql.se"
                        },
                        new
                        {
                            WebpageID = 4,
                            InterestID = 4,
                            PersonID = 3,
                            Webpage = "www.bugs.com"
                        });
                });

            modelBuilder.Entity("Labb4.Models.Interests", b =>
                {
                    b.HasOne("Labb4.Models.Person", "Person")
                        .WithMany("interests")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Labb4.Models.Websites", b =>
                {
                    b.HasOne("Labb4.Models.Person", "persons")
                        .WithOne("website")
                        .HasForeignKey("Labb4.Models.Websites", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb4.Models.Interests", "interests")
                        .WithMany("websites")
                        .HasForeignKey("interestsinterestID");
                });
#pragma warning restore 612, 618
        }
    }
}
