// <auto-generated />
using System;
using Labb4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb4.Models.Interests", b =>
                {
                    b.Property<int>("interestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("details")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("interestID");

                    b.HasIndex("PersonID");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Labb4.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Labb4.Models.PersonInterests", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("interestID")
                        .HasColumnType("int");

                    b.Property<int?>("interestsinterestID")
                        .HasColumnType("int");

                    b.Property<int?>("personID")
                        .HasColumnType("int");

                    b.Property<string>("webpage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("interestsinterestID");

                    b.HasIndex("personID");

                    b.ToTable("personInterests");
                });

            modelBuilder.Entity("Labb4.Models.Interests", b =>
                {
                    b.HasOne("Labb4.Models.Person", null)
                        .WithMany("interests")
                        .HasForeignKey("PersonID");
                });

            modelBuilder.Entity("Labb4.Models.PersonInterests", b =>
                {
                    b.HasOne("Labb4.Models.Interests", "interests")
                        .WithMany()
                        .HasForeignKey("interestsinterestID");

                    b.HasOne("Labb4.Models.Person", "person")
                        .WithMany()
                        .HasForeignKey("personID");
                });
#pragma warning restore 612, 618
        }
    }
}
